import Head from "next/head";
import { useRouter } from "next/router";
import { useMeQuery } from "../generated/graphql";

export default function Home() {
    const { data, loading } = useMeQuery();
    const router = useRouter();
    if (!loading && data?.me != null) {
        router.push("/app");
    }
    return (
        <div>
            <Head>
                <title>Codeday Delhi Project</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex items-center bg-gray-900 border-b border-gray-800">
                <p
                    style={{ fontFamily: "Menlo" }}
                    className="ml-3 text-purple-500 text-xl"
                >
                    me.com
                </p>
                <div className="ml-auto mr-5">
                    <button
                        onClick={() => router.push("/services")}
                        type="submit"
                        className="px-3 py-1.5 my-2 mr-4 border border-gray-700 rounded-md text-gray-300 font-medium text-md bg-gray-800"
                    >
                        All Services
                    </button>
                    <button
                        onClick={() => router.push("/login")}
                        type="submit"
                        className="px-3 py-1.5 my-2 border border-gray-700 rounded-md text-gray-300 font-medium text-md bg-gray-800"
                    >
                        Log in
                    </button>
                    <button
                        onClick={() => router.push("/register")}
                        type="submit"
                        className="px-3 py-1.5 mx-5 my-2 border border-gray-700 rounded-md text-gray-300 font-medium text-md bg-gray-800"
                    >
                        Sign Up
                    </button>
                </div>
            </div>
            <p
                style={{ fontFamily: "Menlo" }}
                className="text-purple-500 text-center mt-20 text-5xl"
            >
                me.com
            </p>
            <p className="text-center mt-5 text-gray-500">
                a genuine product by a genuine team <br />
                <div className="mt-4" />
                Madhur Sapra
                <br />
                Shravyaa Gupta
                <br />
                Divyanshu Maheshwari <br />
                Japroz
                <br />
            </p>
        </div>
    );
}
